version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    env_file:
      - .development.env   
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=todo_dba
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=todo_dev
